#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DisertationProject.Resource", IsApplication=true)]

namespace DisertationProject
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int blue = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int green = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int red = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_forward = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_next = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_play = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_play_over_video = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_previous = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_repeat = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_repeat_not = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_rewind = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_shuffle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_shuffle_not = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_stop = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int repeatToggleSelector = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int shuffleToggleSelector = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int cameraButton = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout1 = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout2 = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout3 = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout4 = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int nextButton = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int pauseButton = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int playButton = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int previousButton = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int repeatButton = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int shuffleButton = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int songListView = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int songPositionSeekBar = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int stopButton = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int textView1 = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Jessica_Jay_Casablanca = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Vaya_Con_Dios_Puerto_Rico = 2131034113;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
